# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(390, 490)
        Dialog.setStyleSheet("background-color: rgb(179, 220, 214);")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 391, 161))
        self.frame.setStyleSheet("background-color: rgb(119, 161, 159);\n")
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(350, 130, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(8)
        font.setItalic(False)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(179, 220, 214);\n"
"font: 81 8pt \"Rockwell Extra Bold\";\n"
"color: rgb(79, 103, 109);\n"
"border-radius: 10px;\n"
"border: 0 0 0;")
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(30, 80, 321, 61))
        self.textEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit.setStyleSheet("background-color: rgb(179, 220, 214);\n"
"font: 0 16pt \"Arial\";\n"
"font-weight: 600;\n"
"color: rgb(79, 103, 109);\n"
"border-radius: 26px;\n"
"border: 0 0 0;\n"
"padding-left: 20;\n"
"padding-top: 15;")
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 10, 321, 61))
        self.label.setStyleSheet("background-color: rgb(179, 220, 214);\n"
"font: 0 6pt \"Arial\";\n"
"font-weight: 600;\n"
"color: rgb(79, 103, 109);\n"
"border-radius: 26px;\n"
"border: 0 0 0;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 390, 121, 41))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    font: 0 16pt \"Arial\";\n"
"    font-weight: 600;\n"
"    color:  rgb(190, 102, 114);\n"
"    border-radius: 20px;\n"
"    border: 4px solid rgb(190, 102, 114);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:  rgba(198, 106, 120, 200);\n"
"    border: 4px solid  rgba(198, 106, 120, 200);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color:  rgb(172, 92, 104);\n"
"    border: 4px solid rgb(172, 92, 104);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(30, 180, 341, 51))
        self.widget.setStyleSheet("background-color: rgb(219, 238, 232);\n"
"font: 0 24pt \"Arial\";\n"
"font-weight: 600;\n"
"color: rgb(190, 102, 114);\n"
"border-radius: 14px;\n"
"padding-left: 10;")
        self.widget.setObjectName("widget")
        self.timeEdit_4 = QtWidgets.QTimeEdit(self.widget)
        self.timeEdit_4.setGeometry(QtCore.QRect(0, 10, 171, 31))
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setGeometry(QtCore.QRect(230, 0, 111, 51))
        self.widget_4.setObjectName("widget_4")
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setGeometry(QtCore.QRect(30, 240, 341, 51))
        self.widget_2.setStyleSheet("background-color: rgb(219, 238, 232);\n"
"font: 0 24pt \"Arial\";\n"
"font-weight: 600;\n"
"color: rgb(190, 102, 114);\n"
"border-radius: 14px;\n"
"padding-left: 10;")
        self.widget_2.setObjectName("widget_2")
        self.timeEdit_5 = QtWidgets.QTimeEdit(self.widget_2)
        self.timeEdit_5.setGeometry(QtCore.QRect(0, 10, 171, 31))
        self.timeEdit_5.setObjectName("timeEdit_5")
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setGeometry(QtCore.QRect(230, 0, 111, 51))
        self.widget_5.setObjectName("widget_5")
        self.widget_3 = QtWidgets.QWidget(Dialog)
        self.widget_3.setGeometry(QtCore.QRect(30, 300, 341, 51))
        self.widget_3.setStyleSheet("background-color: rgb(219, 238, 232);\n"
"font: 0 24pt \"Arial\";\n"
"font-weight: 600;\n"
"color: rgb(190, 102, 114);\n"
"border-radius: 14px;\n"
"padding-left: 10;")
        self.widget_3.setObjectName("widget_3")
        self.timeEdit_6 = QtWidgets.QTimeEdit(self.widget_3)
        self.timeEdit_6.setGeometry(QtCore.QRect(0, 10, 171, 31))
        self.timeEdit_6.setObjectName("timeEdit_6")
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        self.widget_6.setGeometry(QtCore.QRect(230, 0, 111, 51))
        self.widget_6.setObjectName("widget_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "ОК"))
        self.textEdit.setPlaceholderText(_translate("Dialog", "Your answer:"))
        self.pushButton_2.setText(_translate("Dialog", "DONE"))
        self.timeEdit_4.setDisplayFormat(_translate("Dialog", "HH:mm"))
        self.timeEdit_5.setDisplayFormat(_translate("Dialog", "HH:mm"))
        self.timeEdit_6.setDisplayFormat(_translate("Dialog", "HH:mm"))
